#!/bin/sh

set -euf #o pipefail
cd "$REPO_USER_PATH"

OUT=$(find . -type f -name "$FILE_NAME_MARKER" -exec printf "$GIT_USER/" \; -exec /bin/sh -c "dirname -- '{}' | cut -c 3-" \;)
if [ -z "$OUT" ]; then
	echo "No repos found!"
	exit 1
fi
echo "$OUT"
