#!/bin/sh

NEW_REPO="$*"

set -euf #o pipefail
cd "$REPO_USER_PATH"

# TODO(leon): DRY
if ! (echo "$NEW_REPO" | grep -xq '^[a-zA-Z0-9_\-]*$'); then
	echo "Disallowed characters in repo name. Allowed: a-z, A-Z, 0-9, _, -"
	exit 1
fi

if [ -z "$NEW_REPO" ]; then
	echo "No repo name specified"
	exit 1
fi

if [ -e "$NEW_REPO/$FILE_NAME_MARKER" ]; then
	echo "Repo '$NEW_REPO' already exists"
	exit 1
fi

mkdir -- "$NEW_REPO"
cd -- "$NEW_REPO"

git init --bare > /dev/null

echo "$GIT_USER" > "$FILE_NAME_ACCESS_READ"
echo "$GIT_USER" > "$FILE_NAME_ACCESS_WRITE"
touch "$FILE_NAME_MARKER"

echo "$GIT_USER/$NEW_REPO"
